- name: Clear npm cache
  command: npm cache clean --force
  args:
    chdir: app/front

- name: Install NVM
  become: yes
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
  args:
    creates: "/home/runner/.nvm"

- name: Install specific version of Node.js
  become: yes
  shell: "/bin/bash -c 'source ~/.nvm/nvm.sh && nvm install 9.4'"
  args:
    executable: /bin/bash

- name: Install Node.js dependencies
  command: npm install
  args:
    chdir: app/front

- name: Build Angular app
  command: npm run build
  args:
    chdir: app/front
