- name: Clear npm cache
  become: true
  command: npm cache clean --force
  args:
    chdir: app/front

- name: Install NVM
  become: true
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
  args:
    creates: "/home/runner/.nvm"

- name: Load NVM into the shell
  become: true
  shell: |
    source ~/.nvm/nvm.sh
    source ~/.bashrc
  args:
    executable: /bin/bash

- name: Install specific version of Node.js
  become: true
  shell: "/home/runner/.nvm/nvm.sh install 9.4"
  args:
    executable: /bin/bash

- name: Install Node.js dependencies
  become: true
  command: npm install
  args:
    chdir: app/front

- name: Build Angular app
  become: true
  command: npm run build
  args:
    chdir: app/front
