- name: Clear npm cache
  become_user: runner
  command: npm cache clean --force
  args:
    chdir: app/front

- name: Install NVM
  become_user: runner
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
  args:
    creates: "/home/runner/.nvm"

- name: Change permissions of nvm.sh
  become_user: runner
  file:
    path: "/home/runner/.nvm/nvm.sh"
    mode: "u+x"

- name: Load NVM into the shell
  become_user: runner
  shell: |
    source ~/.nvm/nvm.sh
    source ~/.bashrc
  args:
    executable: /bin/bash

- name: Install specific version of Node.js
  become_user: runner
  shell: "/home/runner/.nvm/nvm.sh install 9.4"
  args:
    executable: /bin/bash

- name: Install Node.js dependencies
  become_user: runner
  command: npm install -g npm
  args:
    chdir: app/front

- name: Install Angular CLI globally
  become_user: runner
  command: npm install -g @angular/cli

- name: Build Angular app
  become_user: runner
  command: ng build
  args:
    chdir: app/front
