- name: Update package cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - curl
    - git

- name: Install Node.js via NVM
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && source ~/.bashrc && nvm install 9.4
  args:
    executable: /bin/bash

- name: Download and extract Python 2.7
  shell: |
    wget -O - https://www.python.org/ftp/python/2.7/Python-2.7.tgz | tar -xz -C /usr/local/src
  become: yes

# - name: Configure and install Python 2.7
#   shell: |
#     cd /usr/local/src/Python-2.7
#     ./configure
#     make
#     make install 
- name: Download npm
  shell: |
     apt install npm
  become: yes

- name: Copy front-end files to remote server
  ansible.builtin.copy:
    src:  /SLA_2024/app/front/
    dest: "~/T-NSA-700/front/"
    remote_src: yes

- name: Install front-end dependencies
  npm:
    path: "~/T-NSA-700/front"
    state: present

- name: Start front-end application
  command: npm start
  args:
    chdir: "~/T-NSA-700/front"

