- name: "Install Composer"
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

- name: "Give permissions to composer.json"
  command: sudo chown -R nsa:nsa /var/www/back/composer.json

- name: "Give permissions to composer.lock"
  command: sudo chown -R nsa:nsa /var/www/back/composer.lock

- name: "Ensure bootstrap/cache directory exists"
  become: yes
  file:
    path: /var/www/back/bootstrap/cache
    state: directory
    mode: '0755'

- name: "Ensure bootstrap/cache directory is writable"
  become: yes
  command: sudo chown -R nsa:nsa /var/www/back/bootstrap/cache

- name: "dump reload"
  become: true
  become_user: nsa
  command: composer dump-autoload
  args:
    chdir: /var/www/back

- name: "Update project's dependencies"
  become: yes
  become_user: nsa
  composer:
    command: require
    arguments: laravel/framework:5.8.*
    working_dir: /var/www/back

- name: "Clear project's cache"
  become: true
  become_user: nsa
  command: composer clear-cache
  args:
    chdir: /var/www/back

- name: "Update project"
  become: true
  become_user: nsa
  command: composer update
  args:
    chdir: /var/www/back

- name: "Composer install"
  become: true
  become_user: nsa
  command: composer install
  args:
    chdir: /var/www/back

- name: "Generate key"
  become: yes
  become_user: nsa
  command: sudo php artisan key:generate
  args:
    chdir: /var/www/back