---
- name: "Update apt cache"
  apt:
    update_cache: yes

- name: "Install PHP"
  become: yes
  apt:
    name: {{ php_version }}
    state: present

- name: "Install PHP's extensions"
  apt: name={{ php_version }}-{{ item }}
  with_items:
    - cli
    - pdo
    - mysqli
    - zip
    - gd
    - mbstring
    - curl
    - xml
    - bcmath
    - intl
  state: present


- name: "Install Composer"
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

- name: "Launch composer install"
  shell: cd /var/www/app && sudo composer install

- name: "Restart php-fpm"
  command: service php-fpm restart
