name: Deployment

on:
  push:
    branches: [dev]

jobs:
  deploy:
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: cd_playbook.yml
        directory: ./
        vault_password: T-NSA-700-PAR_24
