name: Run Laravel backend unit tests

on:
  push:
    branches: [dev]

jobs:
  continuous-integration:
    name: Laravel (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1

      - name: Clear Composer cache
        run: |
          cd app/back
          composer clear-cache
          composer update

      - name: Install Composer dependencies
        run: |
          cd app/back
          composer install
          
      - name: Update dependencies
        run: |
          cd app/back
          composer require laravel/framework:5.8.*

      - name: Prepare Laravel Application
        run: |
          cd app/back
          touch .env
          cp ../../.env.ci .env
          php artisan key:generate

      - name: Run Tests
        run: |
          cd app/back
          vendor/bin/phpunit